// <auto-generated />
using ASPSyncCollegeRoom2018.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace ASPSyncCollegeRoom2018.Migrations
{
    [DbContext(typeof(CalendarDBContext))]
    [Migration("20180208223944_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("ASPSyncCollegeRoom2018.Models.Appointment", b =>
                {
                    b.Property<string>("Text")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Id");

                    b.HasKey("Text");

                    b.ToTable("Appointment");
                });

            modelBuilder.Entity("ASPSyncCollegeRoom2018.Models.ScheduleData", b =>
                {
                    b.Property<int>("ProgramId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comments");

                    b.Property<bool>("IsAllDay");

                    b.Property<bool>("IsRecurrence");

                    b.Property<DateTime>("ProgramEndTime");

                    b.Property<string>("ProgramName");

                    b.Property<DateTime>("ProgramStartTime");

                    b.Property<string>("RecurrenceRule");

                    b.HasKey("ProgramId");

                    b.ToTable("ScheduleData");
                });
#pragma warning restore 612, 618
        }
    }
}
